name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - name: Init build submodules
        run: git submodule update --init extern/min-api extern/max-sdk extern/cppzmq extern/libzmq

      - name: Configure
        run: cmake -B build -G Xcode

      - name: Build
        run: cmake --build build --config Release

      - name: List outputs
        run: ls -la externals/

  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - name: Init build submodules
        run: git submodule update --init extern/min-api extern/max-sdk extern/cppzmq extern/libzmq

      - name: Configure
        run: cmake -B build -G "Visual Studio 17 2022" -A x64

      - name: Build
        run: cmake --build build --config Release

      - name: List outputs
        run: ls externals/
